### ISSUE TITLE
SEGFAULT when loading

### ISSUE THREAD

**Issue by tivvit** [mozilla-services/lua_bloom_filter#3]
Hello, 

I wanted to try this lib, but got segfault instead:
```
$ ctest
Test project /home/tivvit/git/lua_bloom_filter/release
    Start 1: test
1/1 Test #1: test .............................***Exception: SegFault  0.01 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.01 sec

The following tests FAILED:
	  1 - test (SEGFAULT)
Errors while running CTest
```
versions:
```
$ gcc --version
gcc (Debian 4.7.2-5) 4.7.2
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
```
$ lua -v
Lua 5.2.1  Copyright (C) 1994-2012 Lua.org, PUC-Rio
```
```
$ cmake --version
cmake version 3.0.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

Valgrind output:
```
$ valgrind lua test.lua
==37033== Memcheck, a memory error detector
==37033== Copyright (C) 2002-2011, and GNU GPL'd, by Julian Seward et al.
==37033== Using Valgrind-3.7.0 and LibVEX; rerun with -h for copyright info
==37033== Command: lua test.lua
==37033==
==37033==
==37033== Process terminating with default action of signal 11 (SIGSEGV)
==37033==  Bad permissions for mapped region at address 0x5AA9D38
==37033==    at 0x411B7C: ??? (in /usr/bin/lua5.2)
==37033==    by 0x5EB149E: bloom_filter_new (in /home/tivvit/git/lua_bloom_filter/bloom_filter.so)
==37033==    by 0x408C31: ??? (in /usr/bin/lua5.2)
==37033==    by 0x412BE3: ??? (in /usr/bin/lua5.2)
==37033==    by 0x408E68: ??? (in /usr/bin/lua5.2)
==37033==    by 0x4084BA: ??? (in /usr/bin/lua5.2)
==37033==    by 0x409094: ??? (in /usr/bin/lua5.2)
==37033==    by 0x406CCC: lua_pcallk (in /usr/bin/lua5.2)
==37033==    by 0x419BC5: ??? (in /usr/bin/lua5.2)
==37033==    by 0x408C31: ??? (in /usr/bin/lua5.2)
==37033==    by 0x412BE3: ??? (in /usr/bin/lua5.2)
==37033==    by 0x408E68: ??? (in /usr/bin/lua5.2)
==37033==
==37033== HEAP SUMMARY:
==37033==     in use at exit: 49,871 bytes in 529 blocks
==37033==   total heap usage: 765 allocs, 236 frees, 87,291 bytes allocated
==37033==
==37033== LEAK SUMMARY:
==37033==    definitely lost: 0 bytes in 0 blocks
==37033==    indirectly lost: 0 bytes in 0 blocks
==37033==      possibly lost: 0 bytes in 0 blocks
==37033==    still reachable: 49,871 bytes in 529 blocks
==37033==         suppressed: 0 bytes in 0 blocks
==37033== Rerun with --leak-check=full to see details of leaked memory
==37033==
==37033== For counts of detected and suppressed errors, rerun with: -v
==37033== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 10 from 7)
Segmentation fault
```

that was on debian wheezy and on mac i got this when building: 
```
Scanning dependencies of target bloom_filter
[ 33%] Building C object CMakeFiles/bloom_filter.dir/lua_bloom_filter.c.o
/tmp/lua_bloom_filter/lua_bloom_filter.c:223:47: error: array has incomplete element type 'const struct luaL_reg'
static const struct luaL_reg bloom_filterlib_f[] =
                                              ^
/tmp/lua_bloom_filter/lua_bloom_filter.c:223:21: note: forward declaration of 'struct luaL_reg'
static const struct luaL_reg bloom_filterlib_f[] =
                    ^
/tmp/lua_bloom_filter/lua_bloom_filter.c:231:47: error: array has incomplete element type 'const struct luaL_reg'
static const struct luaL_reg bloom_filterlib_m[] =
                                              ^
/tmp/lua_bloom_filter/lua_bloom_filter.c:223:21: note: forward declaration of 'struct luaL_reg'
static const struct luaL_reg bloom_filterlib_f[] =
                    ^
/tmp/lua_bloom_filter/lua_bloom_filter.c:252:3: error: implicit declaration of function 'luaL_register' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  luaL_register(lua, NULL, bloom_filterlib_m);
  ^
3 errors generated.
make[2]: *** [CMakeFiles/bloom_filter.dir/lua_bloom_filter.c.o] Error 1
make[1]: *** [CMakeFiles/bloom_filter.dir/all] Error 2
make: *** [all] Error 2
```

I would love to help but I have no idea where to look

**Comment by trink** [comment]
Interesting, it shouldn't even build with lua5.2 since luaL_reg is no longer defined. We use these and the other Mozilla service libraries exclusively with Lua 5.1.  The libraries also use some features and behaviour that was deprecated in 5.2.  

I will look into adding support for 5.2 but is pretty low priority.

**Comment by trink** [comment]
I will accept a PR for 5.2/3 compatibility but I don't have the cycles to do the work.
